import { PlantCareInfo } from '@/types';

export const CARE_DATA: PlantCareInfo[] = [
  {
    id: 'monstera-deliciosa',
    commonName: 'Swiss Cheese Plant',
    scientificName: 'Monstera deliciosa',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 18,
    tempMax: 30,
    soil: 'Well-draining potting mix with perlite',
    humidity: 'high',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia quando il primo strato di terra è asciutto. Nebulizza le foglie per aumentare l\'umidità. Pulisci le foglie con un panno umido per mantenerle lucide.',
      en: 'Water when the top inch of soil is dry. Mist leaves to increase humidity. Wipe leaves with a damp cloth to keep them glossy.',
    },
    aliases: ['Monstera', 'Split-leaf philodendron'],
    seasonalTemps: [
      { season: 'spring', minTemp: 15, maxTemp: 22 },
      { season: 'summer', minTemp: 20, maxTemp: 28 },
      { season: 'autumn', minTemp: 15, maxTemp: 22 },
      { season: 'winter', minTemp: 12, maxTemp: 18 },
    ],
    fertilization: {
      schedule: {
        it: 'Ogni 2 settimane in primavera e estate, sospendere in autunno e inverno.',
        en: 'Every 2 weeks in spring and summer, pause in autumn and winter.',
      },
      type: {
        it: 'Fertilizzante liquido bilanciato diluito a metà dose.',
        en: 'Balanced liquid fertilizer diluted to half strength.',
      },
    },
    pruning: {
      when: {
        it: 'Primavera o inizio estate, quando la pianta è in fase di crescita attiva.',
        en: 'Spring or early summer, when the plant is actively growing.',
      },
      how: {
        it: 'Rimuovere le foglie gialle o danneggiate alla base del picciolo con forbici pulite.',
        en: 'Remove yellowed or damaged leaves at the base of the petiole with clean scissors.',
      },
    },
    pests: [
      {
        name: { it: 'Ragnetto rosso', en: 'Spider Mite' },
        description: {
          it: 'Piccoli punti gialli sulle foglie, ragnatele sottili sul retro.',
          en: 'Tiny yellow spots on leaves, fine webbing on leaf undersides.',
        },
        remedy: {
          it: 'Aumentare l\'umidità. Trattare con sapone insetticida o neem oil diluito, coprendo bene il retro delle foglie.',
          en: 'Increase humidity. Treat with insecticidal soap or diluted neem oil, covering leaf undersides well.',
        },
      },
      {
        name: { it: 'Cocciniglia', en: 'Mealybug' },
        description: {
          it: 'Masse cotonose bianche nelle ascelle delle foglie o lungo i gambi.',
          en: 'White cottony masses in leaf axils or along stems.',
        },
        remedy: {
          it: 'Rimuovere manualmente con un cotton fioc imbevuto di alcool isopropilico. Trattare poi con neem oil.',
          en: 'Remove manually with an isopropyl alcohol-soaked cotton swab. Follow up with neem oil treatment.',
        },
      },
    ],
  },
  {
    id: 'ficus-lyrata',
    commonName: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 16,
    tempMax: 30,
    soil: 'Rich, well-draining potting soil',
    humidity: 'medium',
    difficulty: 'hard',
    toxicPets: true,
    tips: {
      it: 'Mantieni in una posizione luminosa e stabile — odia essere spostato. Annaffia uniformemente e lascia asciugare leggermente tra un\'annaffiatura e l\'altra.',
      en: 'Keep in a bright, stable spot — it hates being moved. Water evenly and allow slight drying between waterings.',
    },
  },
  {
    id: 'sansevieria-trifasciata',
    commonName: "Snake Plant",
    scientificName: 'Sansevieria trifasciata',
    waterFrequencyDays: 21,
    sunlight: 'low-light',
    tempMin: 10,
    tempMax: 35,
    soil: 'Cactus or succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia raramente e lascia asciugare completamente il terreno tra un\'annaffiatura e l\'altra. Tollera la scarsa luce ma cresce meglio con luce indiretta brillante.',
      en: 'Water sparingly and let soil dry completely between waterings. Tolerates low light but grows best with bright indirect light.',
    },
    aliases: ["Mother-in-law's tongue", 'Dracaena trifasciata'],
  },
  {
    id: 'spathiphyllum-wallisii',
    commonName: 'Peace Lily',
    scientificName: 'Spathiphyllum wallisii',
    waterFrequencyDays: 7,
    sunlight: 'low-light',
    tempMin: 15,
    tempMax: 30,
    soil: 'Rich, well-draining potting soil',
    humidity: 'high',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia quando le foglie iniziano a drooping leggermente. Ama l\'umidità alta e la luce indiretta. Fiorisce meglio con poca luce.',
      en: 'Water when leaves start to droop slightly. Loves high humidity and indirect light. Blooms better with low light.',
    },
    aliases: ['Spathiphyllum', 'Peace lily'],
  },
  {
    id: 'dracaena-marginata',
    commonName: 'Dragon Tree',
    scientificName: 'Dracaena marginata',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Loamy, well-draining soil',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia moderatamente. Evita l\'acqua con fluoro o cloro — usa acqua piovana o acqua rimasta aperta overnight. Tollera la poca luce ma preferisce luce indiretta.',
      en: 'Water moderately. Avoid fluoride or chlorinated water — use rainwater or water left open overnight. Tolerates low light but prefers indirect light.',
    },
    aliases: ['Madagascar dragon tree'],
  },
  {
    id: 'pothos-aureus',
    commonName: 'Pothos',
    scientificName: 'Epipremnum aureum',
    waterFrequencyDays: 7,
    sunlight: 'low-light',
    tempMin: 15,
    tempMax: 30,
    soil: 'Any well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Quasi indistruttibile! Annaffia quando il terreno è asciutto al tatto. Cresce in quasi tutte le condizioni di luce. Perfetto per principianti.',
      en: 'Nearly indestructible! Water when soil feels dry to the touch. Grows in almost any light condition. Perfect for beginners.',
    },
    aliases: ['Golden pothos', 'Devil\'s ivy'],
  },
  {
    id: 'zamioculcas-zamiifolia',
    commonName: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    waterFrequencyDays: 21,
    sunlight: 'low-light',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Tollera la siccità molto bene grazie ai rizomi sotterranei. Annaffia pochissimo e mai lasciare in acqua stagnante. Ottimo per ambienti con poca luce.',
      en: 'Very drought tolerant thanks to underground rhizomes. Water very little and never leave in standing water. Great for low-light environments.',
    },
    aliases: ['Zanzibar gem'],
  },
  {
    id: 'philodendron-hederaceum',
    commonName: 'Heartleaf Philodendron',
    scientificName: 'Philodendron hederaceum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Moist, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia quando il primo strato di terra è asciutto. Pianta rampicante o ricadente, ama crescere su un supporto di muschio. Rimuovi le foglie gialle.',
      en: 'Water when the top layer of soil is dry. A climbing or trailing plant, it loves growing on a moss pole. Remove yellow leaves.',
    },
    aliases: ['Sweetheart plant', 'Philodendron scandens'],
  },
  {
    id: 'aloe-vera',
    commonName: 'Aloe Vera',
    scientificName: 'Aloe vera',
    waterFrequencyDays: 21,
    sunlight: 'full-sun',
    tempMin: 13,
    tempMax: 35,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia abbondantemente ma raramente — lascia asciugare completamente tra le annaffiature. Ama la luce solare diretta. Non annaffiare d\'inverno.',
      en: 'Water deeply but infrequently — let soil dry out completely between waterings. Loves direct sunlight. Do not water in winter.',
    },
  },
  {
    id: 'chlorophytum-comosum',
    commonName: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 30,
    soil: 'Loamy, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Molto tollerante e adattabile. Annaffia regolarmente in estate, meno in inverno. Produce "bambini" appesi che puoi trapiantare facilmente.',
      en: 'Very tolerant and adaptable. Water regularly in summer, less in winter. Produces hanging "babies" that you can easily propagate.',
    },
    aliases: ['Ribbon plant', 'Airplane plant'],
  },
  {
    id: 'crassula-ovata',
    commonName: 'Jade Plant',
    scientificName: 'Crassula ovata',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Sandy, well-draining succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Pianta succulenta che accumula acqua nelle foglie. Annaffia moderatamente e lascia asciugare tra le annaffiature. Ama la luce solare diretta.',
      en: 'A succulent that stores water in its leaves. Water moderately and allow drying between waterings. Loves direct sunlight.',
    },
    aliases: ['Money plant', 'Lucky plant'],
  },
  {
    id: 'calathea-orbifolia',
    commonName: 'Calathea',
    scientificName: 'Calathea orbifolia',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 18,
    tempMax: 30,
    soil: 'Well-draining, slightly moist potting mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Ama l\'umidità alta e la luce indiretta. Usa acqua filtrata o piovana — il fluoro può bruciare le foglie. Le foglie si chiudono di notte.',
      en: 'Loves high humidity and indirect light. Use filtered or rainwater — fluoride can burn leaves. Leaves close at night.',
    },
    aliases: ['Prayer plant', 'Goeppertia orbifolia'],
  },
  {
    id: 'ficus-elastica',
    commonName: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia quando il terreno è asciutto in superficie. Pulisci le foglie grandi e lucide con un panno umido. Evita temperature fredde e correnti d\'aria.',
      en: 'Water when soil surface is dry. Wipe the large glossy leaves with a damp cloth. Avoid cold temperatures and drafts.',
    },
    aliases: ['Rubber fig', 'Rubber tree'],
  },
  {
    id: 'hedera-helix',
    commonName: 'English Ivy',
    scientificName: 'Hedera helix',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 25,
    soil: 'Moist, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Preferisce temperature fresche. Annaffia regolarmente mantenendo il terreno leggermente umido. Può crescere in cestini appesi o rampicante.',
      en: 'Prefers cool temperatures. Water regularly keeping soil slightly moist. Can grow in hanging baskets or as a climber.',
    },
  },
  {
    id: 'dieffenbachia-seguine',
    commonName: 'Dumb Cane',
    scientificName: 'Dieffenbachia seguine',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'ATTENZIONE: la linfa è tossica e irritante. Annaffia regolarmente ma evita il ristagno. Preferisce la luce indiretta brillante.',
      en: 'CAUTION: sap is toxic and irritating. Water regularly but avoid waterlogging. Prefers bright indirect light.',
    },
    aliases: ['Dieffenbachia'],
  },
  {
    id: 'aglaonema-commutatum',
    commonName: 'Chinese Evergreen',
    scientificName: 'Aglaonema commutatum',
    waterFrequencyDays: 10,
    sunlight: 'low-light',
    tempMin: 16,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Una delle piante da interno più resistenti. Annaffia moderatamente. Le varietà più scure tollerano meglio la poca luce rispetto a quelle variegatate.',
      en: 'One of the toughest houseplants. Water moderately. Darker varieties tolerate low light better than variegated ones.',
    },
    aliases: ['Aglaonema'],
  },
  {
    id: 'howea-forsteriana',
    commonName: 'Kentia Palm',
    scientificName: 'Howea forsteriana',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 12,
    tempMax: 30,
    soil: 'Rich, well-draining mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Palma elegante e molto tollerante. Annaffia regolarmente in estate, meno in inverno. Manda via l\'acqua in eccesso dal sottovaso.',
      en: 'Elegant and very tolerant palm. Water regularly in summer, less in winter. Empty excess water from saucer.',
    },
    aliases: ['Paradise palm'],
  },
  {
    id: 'rhapis-excelsa',
    commonName: 'Lady Palm',
    scientificName: 'Rhapis excelsa',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Palma compatta ideale per interni. Tollera la poca luce meglio di altre palme. Annaffia con moderazione, evitando il ristagno idrico.',
      en: 'Compact palm ideal for indoors. Tolerates low light better than most palms. Water moderately, avoiding waterlogging.',
    },
    aliases: ['Broadleaf lady palm'],
  },
  {
    id: 'chamaedorea-elegans',
    commonName: 'Parlour Palm',
    scientificName: 'Chamaedorea elegans',
    waterFrequencyDays: 10,
    sunlight: 'low-light',
    tempMin: 12,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Palma ideale per ambienti con poca luce. Mantieni il terreno leggermente umido ma non saturato. Nebulizza regolarmente per prevenire gli acari.',
      en: 'Ideal palm for low-light environments. Keep soil slightly moist but not saturated. Mist regularly to prevent spider mites.',
    },
    aliases: ['Neanthe bella palm'],
  },
  {
    id: 'yucca-elephantipes',
    commonName: 'Spineless Yucca',
    scientificName: 'Yucca elephantipes',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 7,
    tempMax: 35,
    soil: 'Sandy, well-draining mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Ama la luce solare diretta e tollera la siccità. Annaffia poco e regolarmente. Resistente a temperature fredde. Evita il ristagno.',
      en: 'Loves direct sunlight and tolerates drought. Water sparingly and regularly. Resistant to cold temperatures. Avoid waterlogging.',
    },
    aliases: ['Giant yucca', 'Soft-tipped yucca'],
  },
  {
    id: 'schefflera-arboricola',
    commonName: 'Umbrella Plant',
    scientificName: 'Schefflera arboricola',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Annaffia quando il terreno è parzialmente asciutto. Tollera la poca luce ma preferisce luce indiretta brillante. Ruota la pianta per una crescita uniforme.',
      en: 'Water when soil is partially dry. Tolerates low light but prefers bright indirect light. Rotate plant for even growth.',
    },
    aliases: ['Dwarf umbrella tree'],
  },
  {
    id: 'oxalis-triangularis',
    commonName: 'Purple Shamrock',
    scientificName: 'Oxalis triangularis',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 25,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Le foglie triangolari si chiudono di notte. Annaffia regolarmente durante la crescita attiva. Va in dormienza in estate — riduci le annaffiature.',
      en: 'Triangular leaves close at night. Water regularly during active growth. Goes dormant in summer — reduce watering.',
    },
    aliases: ['False shamrock', 'Love plant'],
  },
  {
    id: 'tradescantia-zebrina',
    commonName: 'Wandering Dude',
    scientificName: 'Tradescantia zebrina',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Cresce rapidamente e si propaga facilmente in acqua. Ama la luce per mantenere i colori vibranti. Annaffia regolarmente.',
      en: 'Grows fast and propagates easily in water. Loves light to maintain vibrant colors. Water regularly.',
    },
    aliases: ['Spiderwort', 'Inch plant', 'Tradescantia fluminensis'],
  },
  {
    id: 'begonia-rex',
    commonName: 'Rex Begonia',
    scientificName: 'Begonia rex',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 27,
    soil: 'Light, well-draining mix with perlite',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Annaffia dalla base per evitare marcescenza delle foglie. Non nebulizzare — aumenta il rischio di funghi. Ama la luce diffusa e brillante.',
      en: 'Water from the base to avoid leaf rot. Do not mist — increases risk of fungal issues. Loves diffused bright light.',
    },
    aliases: ['King begonia', 'Fancy-leaf begonia'],
  },
  {
    id: 'saintpaulia-ionantha',
    commonName: 'African Violet',
    scientificName: 'Saintpaulia ionantha',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 27,
    soil: 'African violet specialty mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Annaffia dalla base con acqua tiepida. Evita l\'acqua sulle foglie — crea macchie. Ama la luce indiretta brillante. Rimuovi i fiori appassiti.',
      en: 'Water from the base with lukewarm water. Avoid water on leaves — causes spots. Loves bright indirect light. Remove spent flowers.',
    },
    aliases: ['Saintpaulia'],
  },
  {
    id: 'cyclamen-persicum',
    commonName: 'Cyclamen',
    scientificName: 'Cyclamen persicum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 20,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta da fiore invernale. Ama il fresco — non oltre i 20°C. Annaffia dalla base evitando il tubero. Va in dormienza in estate.',
      en: 'Winter flowering plant. Loves cool conditions — not above 20°C. Water from base avoiding the tuber. Goes dormant in summer.',
    },
  },
  {
    id: 'anthurium-andraeanum',
    commonName: 'Flamingo Flower',
    scientificName: 'Anthurium andraeanum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Orchid bark mix with perlite',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Ama l\'umidità alta e la luce indiretta brillante. Annaffia quando il terreno è quasi asciutto. Evita l\'esposizione diretta al sole che brucia le foglie.',
      en: 'Loves high humidity and bright indirect light. Water when soil is almost dry. Avoid direct sun exposure which burns leaves.',
    },
    aliases: ['Anthurium', 'Tailflower'],
  },
  {
    id: 'chrysanthemum-morifolium',
    commonName: 'Chrysanthemum',
    scientificName: 'Chrysanthemum morifolium',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 22,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta da interno temporanea da far rifiorire all\'esterno. Mantieni il terreno uniformemente umido. Ama la luce brillante. Rimuovi i fiori appassiti.',
      en: 'Temporary indoor plant best re-bloomed outdoors. Keep soil evenly moist. Loves bright light. Deadhead spent flowers.',
    },
    aliases: ['Florist\'s chrysanthemum', 'Mum'],
  },
  {
    id: 'guzmania-lingulata',
    commonName: 'Scarlet Star Bromeliad',
    scientificName: 'Guzmania lingulata',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 16,
    tempMax: 30,
    soil: 'Bromeliad or orchid mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Annaffia nella rosetta centrale (il "vaso" naturale) e tieni il terreno leggermente umido. Ama l\'umidità alta. Fiorisce una sola volta poi produce polloni.',
      en: 'Water in the central rosette (the natural "cup") and keep soil slightly moist. Loves high humidity. Blooms once then produces pups.',
    },
    aliases: ['Bromeliad'],
  },
  {
    id: 'aechmea-fasciata',
    commonName: 'Urn Plant',
    scientificName: 'Aechmea fasciata',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Bromeliad mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Mantieni acqua fresca nella rosetta centrale. Annaffia il terreno solo occasionalmente. Ama la luce indiretta brillante e l\'umidità alta.',
      en: 'Keep fresh water in the central rosette. Water soil only occasionally. Loves bright indirect light and high humidity.',
    },
    aliases: ['Silver vase plant'],
  },
  {
    id: 'tillandsia-usneoides',
    commonName: 'Spanish Moss',
    scientificName: 'Tillandsia usneoides',
    waterFrequencyDays: 3,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 30,
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Pianta aerea che non ha bisogno di terra. Nebulizza ogni 2-3 giorni o immergi in acqua per 20 minuti settimanalmente. Ama l\'aria fresca e umida.',
      en: 'Air plant that needs no soil. Mist every 2-3 days or soak in water for 20 minutes weekly. Loves fresh, humid air.',
    },
    aliases: ['Air plant', 'Tillandsia'],
  },
  {
    id: 'echeveria-elegans',
    commonName: 'Mexican Snowball',
    scientificName: 'Echeveria elegans',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 5,
    tempMax: 30,
    soil: 'Sandy, well-draining succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Succulenta rosetta elegante. Annaffia profondamente ma raramente. Ama la luce solare diretta. Evita l\'acqua ristagno che causa marcescenza.',
      en: 'Elegant rosette succulent. Water deeply but rarely. Loves direct sunlight. Avoid standing water which causes rot.',
    },
    aliases: ['Echeveria'],
  },
  {
    id: 'haworthia-attenuata',
    commonName: 'Zebra Plant',
    scientificName: 'Haworthia attenuata',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Sandy, well-draining succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Succulenta ideale per interni. Tollera la poca luce meglio di altre succulente. Annaffia raramente lasciando asciugare completamente il terreno.',
      en: 'Ideal succulent for indoors. Tolerates lower light than most succulents. Water rarely letting soil dry out completely.',
    },
    aliases: ['Haworthia'],
  },
  {
    id: 'sedum-morganianum',
    commonName: "Burro's Tail",
    scientificName: 'Sedum morganianum',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Succulenta ricadente bellissima per cestini appesi. Le foglie cadono facilmente — posiziona con cura. Annaffia raramente in estate, quasi mai in inverno.',
      en: 'Beautiful trailing succulent for hanging baskets. Leaves fall easily — position carefully. Water rarely in summer, almost never in winter.',
    },
    aliases: ["Donkey's tail", 'Lamb\'s tail'],
  },
  {
    id: 'mammillaria-crinita',
    commonName: 'Pincushion Cactus',
    scientificName: 'Mammillaria crinita',
    waterFrequencyDays: 21,
    sunlight: 'full-sun',
    tempMin: 5,
    tempMax: 40,
    soil: 'Cactus and succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Cactus molto resistente. Annaffia solo quando il terreno è completamente asciutto. Ama la luce solare diretta. In inverno riduci le annaffiature.',
      en: 'Very resilient cactus. Water only when soil is completely dry. Loves direct sunlight. Reduce watering in winter.',
    },
    aliases: ['Mammillaria'],
  },
  {
    id: 'gymnocalycium-mihanovichii',
    commonName: 'Moon Cactus',
    scientificName: 'Gymnocalycium mihanovichii',
    waterFrequencyDays: 21,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 35,
    soil: 'Well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Cactus variegato innestato su un\'altra pianta. Non tollera la luce solare diretta intensa. Annaffia raramente e assicurati un buon drenaggio.',
      en: 'Variegated cactus grafted onto another plant. Does not tolerate intense direct sunlight. Water rarely and ensure good drainage.',
    },
    aliases: ['Chin cactus', 'Ruby ball cactus'],
  },
  {
    id: 'cereus-peruvianus',
    commonName: 'Peruvian Apple Cactus',
    scientificName: 'Cereus repandus',
    waterFrequencyDays: 21,
    sunlight: 'full-sun',
    tempMin: 5,
    tempMax: 40,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Cactus colonnare a crescita rapida. Ama la luce solare diretta. Annaffia raramente in estate, per niente in inverno. Proteggi dal gelo.',
      en: 'Fast-growing columnar cactus. Loves direct sunlight. Water rarely in summer, not at all in winter. Protect from frost.',
    },
    aliases: ['Cereus', 'Column cactus'],
  },
  {
    id: 'opuntia-microdasys',
    commonName: 'Bunny Ears Cactus',
    scientificName: 'Opuntia microdasys',
    waterFrequencyDays: 21,
    sunlight: 'full-sun',
    tempMin: 5,
    tempMax: 40,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Attenzione ai glochidi (piccole spine) che si conficcano facilmente nella pelle. Usa guanti. Ama molta luce solare. Annaffia pochissimo.',
      en: 'Beware of glochids (tiny spines) that embed easily in skin. Use gloves. Loves lots of sunlight. Water very little.',
    },
    aliases: ['Polka dot cactus'],
  },
  {
    id: 'peperomia-obtusifolia',
    commonName: 'Baby Rubber Plant',
    scientificName: 'Peperomia obtusifolia',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Light, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Molto tollerante e compatta. Annaffia poco — accumula acqua nelle foglie carnose. Perfetta per scrivania o mensole. Evita il sole diretto.',
      en: 'Very tolerant and compact. Water sparingly — stores water in fleshy leaves. Perfect for desks or shelves. Avoid direct sun.',
    },
    aliases: ['Peperomia'],
  },
  {
    id: 'peperomia-caperata',
    commonName: 'Ripple Peperomia',
    scientificName: 'Peperomia caperata',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Light, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Foglie rugose e ornamentali. Annaffia moderatamente lasciando asciugare tra le annaffiature. Compatta e perfetta per spazi ridotti.',
      en: 'Attractive ridged leaves. Water moderately letting soil dry between waterings. Compact and perfect for small spaces.',
    },
  },
  {
    id: 'hoya-carnosa',
    commonName: 'Wax Plant',
    scientificName: 'Hoya carnosa',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining mix with perlite',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta rampicante con fiori profumati a forma di stella. Non rimuovere i peduncoli fiorali — rifiorisce dagli stessi. Annaffia poco in inverno.',
      en: 'Climbing plant with fragrant star-shaped flowers. Do not remove flower stalks — it rebloms from the same ones. Water little in winter.',
    },
    aliases: ['Porcelain flower', 'Hindu rope'],
  },
  {
    id: 'maranta-leuconeura',
    commonName: "Prayer Plant",
    scientificName: 'Maranta leuconeura',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 16,
    tempMax: 28,
    soil: 'Moist, well-draining potting mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Le foglie si alzano di notte come mani in preghiera. Ama l\'umidità alta e la luce bassa. Usa acqua a temperatura ambiente. Nebulizza regolarmente.',
      en: 'Leaves raise at night like hands in prayer. Loves high humidity and low light. Use room-temperature water. Mist regularly.',
    },
    aliases: ['Herringbone plant', 'Ten commandments'],
  },
  {
    id: 'calathea-lancifolia',
    commonName: 'Rattlesnake Plant',
    scientificName: 'Goeppertia lancifolia',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 16,
    tempMax: 28,
    soil: 'Moist, well-draining potting mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Foglie lunghe con motivo a rattlesnake. Ama l\'umidità alta. Usa acqua distillata o piovana. Mantieni lontana da correnti d\'aria fredda.',
      en: 'Long leaves with rattlesnake pattern. Loves high humidity. Use distilled or rainwater. Keep away from cold drafts.',
    },
    aliases: ['Calathea lancifolia'],
  },
  {
    id: 'strelitzia-reginae',
    commonName: 'Bird of Paradise',
    scientificName: 'Strelitzia reginae',
    waterFrequencyDays: 10,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta tropicale spettacolare. Ama molta luce solare diretta per fiorire. Annaffia abbondantemente in estate, riduci in inverno. Ha bisogno di spazio.',
      en: 'Spectacular tropical plant. Needs lots of direct sunlight to bloom. Water abundantly in summer, reduce in winter. Needs space.',
    },
    aliases: ['Strelitzia', 'Crane flower'],
  },
  {
    id: 'fatsia-japonica',
    commonName: 'Japanese Aralia',
    scientificName: 'Fatsia japonica',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 0,
    tempMax: 25,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta resistente al freddo. Annaffia regolarmente in estate, meno in inverno. Ama la luce indiretta. Può stare anche in corridoi freschi.',
      en: 'Cold-resistant plant. Water regularly in summer, less in winter. Loves indirect light. Can thrive in cool hallways.',
    },
    aliases: ['Fatsia', 'Paper plant'],
  },
  {
    id: 'croton-variegatum',
    commonName: 'Croton',
    scientificName: 'Codiaeum variegatum',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: 16,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: true,
    tips: {
      it: 'Foglie multicolori vivaci. Ama molta luce per mantenere i colori. Annaffia regolarmente e mantieni umidità alta. Odia il freddo e gli spostamenti.',
      en: 'Vivid multicolored leaves. Loves lots of light to maintain colors. Water regularly and maintain high humidity. Hates cold and being moved.',
    },
    aliases: ['Garden croton', 'Joseph\'s coat'],
  },
  {
    id: 'alocasia-amazonica',
    commonName: "African Mask Plant",
    scientificName: 'Alocasia amazonica',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 18,
    tempMax: 30,
    soil: 'Well-draining aroid mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: true,
    tips: {
      it: 'Foglie spettacolari con venature bianche. Ama umidità alta e calore. Annaffia con moderazione. In inverno può andare in dormienza.',
      en: 'Spectacular leaves with white veining. Loves high humidity and warmth. Water moderately. May go dormant in winter.',
    },
    aliases: ['Elephant ear', 'Alocasia polly'],
  },
  {
    id: 'caladium-bicolor',
    commonName: 'Caladium',
    scientificName: 'Caladium bicolor',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 18,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Foglie colorate e scenografiche. Ama il calore e l\'umidità. Va in dormienza in autunno — riduci le annaffiature. Conserva i tuberi in luogo asciutto.',
      en: 'Colorful and dramatic leaves. Loves heat and humidity. Goes dormant in autumn — reduce watering. Store tubers in a dry place.',
    },
    aliases: ['Elephant ears', 'Angel wings'],
  },
  {
    id: 'pilea-peperomioides',
    commonName: 'Chinese Money Plant',
    scientificName: 'Pilea peperomioides',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 28,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta rotonda e carina che produce polloni facilmente. Ruota regolarmente per crescita uniforme. Annaffia quando il terreno è quasi asciutto.',
      en: 'Round and cute plant that produces offsets easily. Rotate regularly for even growth. Water when soil is nearly dry.',
    },
    aliases: ['UFO plant', 'Pancake plant'],
  },
  {
    id: 'fittonia-albivenis',
    commonName: 'Nerve Plant',
    scientificName: 'Fittonia albivenis',
    waterFrequencyDays: 5,
    sunlight: 'shade',
    tempMin: 16,
    tempMax: 28,
    soil: 'Moist, well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Foglie con venature contrastanti. Ama l\'umidità alta e la luce bassa. Annaffia frequentemente. Perfetta per terrari. Droop drammaticamente se asciutta.',
      en: 'Leaves with contrasting veins. Loves high humidity and low light. Water frequently. Perfect for terrariums. Dramatically droops when dry.',
    },
    aliases: ['Mosaic plant'],
  },
  {
    id: 'asplenium-nidus',
    commonName: "Bird's Nest Fern",
    scientificName: 'Asplenium nidus',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 15,
    tempMax: 28,
    soil: 'Moist, well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Felce con fronde lisce e ondulate. Ama l\'umidità alta e la luce bassa. Annaffia intorno alla base, non nella rosetta. Mantieni il terreno umido.',
      en: 'Fern with smooth wavy fronds. Loves high humidity and low light. Water around the base, not in the rosette. Keep soil moist.',
    },
    aliases: ['Bird\'s nest fern'],
  },
  {
    id: 'nephrolepis-exaltata',
    commonName: "Boston Fern",
    scientificName: 'Nephrolepis exaltata',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 25,
    soil: 'Moist, rich potting mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Felce classica con fronde lunghe e ricadenti. Ha bisogno di molta umidità e luce indiretta. Nebulizza spesso. Mantieni il terreno sempre umido.',
      en: 'Classic fern with long trailing fronds. Needs lots of humidity and indirect light. Mist often. Keep soil consistently moist.',
    },
    aliases: ['Sword fern', 'Boston fern'],
  },
  {
    id: 'adiantum-raddianum',
    commonName: 'Maidenhair Fern',
    scientificName: 'Adiantum raddianum',
    waterFrequencyDays: 5,
    sunlight: 'shade',
    tempMin: 15,
    tempMax: 25,
    soil: 'Moist, well-draining mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Felce delicata con foglioline tonde su steli neri. Ama l\'umidità altissima. Annaffia frequentemente. Odia correnti d\'aria e secchezza.',
      en: 'Delicate fern with round leaflets on black stems. Loves very high humidity. Water frequently. Hates drafts and dryness.',
    },
    aliases: ['Delta maidenhair fern'],
  },
  {
    id: 'platycerium-bifurcatum',
    commonName: 'Staghorn Fern',
    scientificName: 'Platycerium bifurcatum',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 30,
    soil: 'Sphagnum moss or well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Epifita che cresce su legno o muschio. Annaffia immergendo completamente in acqua per 15 minuti ogni settimana in estate. Non bagnare il fronte marrone scudo.',
      en: 'Epiphyte that grows on wood or moss. Water by fully submerging in water for 15 minutes weekly in summer. Do not wet the brown shield frond.',
    },
    aliases: ['Elkhorn fern'],
  },
  {
    id: 'asparagus-setaceus',
    commonName: 'Asparagus Fern',
    scientificName: 'Asparagus setaceus',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 28,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Non è una vera felce ma assomiglia ad una. Cresce vigorosa e necessita di supporto. Annaffia regolarmente. Le bacche rosse sono tossiche.',
      en: 'Not a true fern but looks like one. Grows vigorously and needs support. Water regularly. Red berries are toxic.',
    },
    aliases: ['Lace fern', 'Climbing asparagus'],
  },
  {
    id: 'syngonium-podophyllum',
    commonName: 'Arrowhead Plant',
    scientificName: 'Syngonium podophyllum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Giovane cresce come rosetta, poi diventa rampicante. Annaffia quando il terreno è parzialmente asciutto. Ama l\'umidità. Pinzare per mantenere compatta.',
      en: 'Young it grows as a rosette, then becomes climbing. Water when soil is partially dry. Loves humidity. Pinch to keep compact.',
    },
    aliases: ['Arrowhead vine', 'Goosefoot plant'],
  },
  {
    id: 'scindapsus-pictus',
    commonName: 'Satin Pothos',
    scientificName: 'Scindapsus pictus',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Foglie grigio-verdi con macchie argentate. Simile al pothos ma più lento. Annaffia quando il terreno è quasi asciutto. Tollera la poca luce.',
      en: 'Gray-green leaves with silver spots. Similar to pothos but slower. Water when soil is nearly dry. Tolerates low light.',
    },
    aliases: ['Silver pothos', 'Silver vine'],
  },
  {
    id: 'senecio-rowleyanus',
    commonName: 'String of Pearls',
    scientificName: 'Senecio rowleyanus',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 28,
    soil: 'Sandy, well-draining succulent mix',
    humidity: 'low',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Succulenta ricadente con foglie a forma di perle. Annaffia raramente. Ama luce brillante indiretta. Ottima per cestini appesi. Molto sensibile al marciume.',
      en: 'Trailing succulent with pearl-shaped leaves. Water rarely. Loves bright indirect light. Great for hanging baskets. Very sensitive to rot.',
    },
    aliases: ['Curio rowleyanus'],
  },
  {
    id: 'curio-radicans',
    commonName: 'String of Bananas',
    scientificName: 'Curio radicans',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Sandy, well-draining succulent mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Succulenta ricadente con foglie a forma di banana. Cresce più veloce di String of Pearls. Annaffia raramente. Ama molta luce indiretta brillante.',
      en: 'Trailing succulent with banana-shaped leaves. Grows faster than String of Pearls. Water rarely. Loves lots of bright indirect light.',
    },
    aliases: ['Senecio radicans'],
  },
  {
    id: 'dischidia-ruscifolia',
    commonName: 'Million Hearts',
    scientificName: 'Dischidia ruscifolia',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining orchid bark mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Pianta epifita con piccole foglie a cuore. Ama l\'umidità e la luce indiretta brillante. Annaffia quando il substrato è quasi asciutto.',
      en: 'Epiphyte with small heart-shaped leaves. Loves humidity and bright indirect light. Water when substrate is nearly dry.',
    },
  },
  {
    id: 'ctenanthe-burle-marxii',
    commonName: 'Fishbone Prayer Plant',
    scientificName: 'Ctenanthe burle-marxii',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 16,
    tempMax: 28,
    soil: 'Moist, well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Foglie con bellissimo pattern a lisca di pesce. Come tutte le Marantaceae alza le foglie di notte. Ama l\'umidità alta e la luce bassa.',
      en: 'Leaves with beautiful fishbone pattern. Like all Marantaceae it raises leaves at night. Loves high humidity and low light.',
    },
    aliases: ['Ctenanthe', 'Never-never plant'],
  },
  {
    id: 'stromanthe-sanguinea',
    commonName: 'Tricolor Stromanthe',
    scientificName: 'Stromanthe sanguinea',
    waterFrequencyDays: 7,
    sunlight: 'shade',
    tempMin: 16,
    tempMax: 28,
    soil: 'Moist, well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Foglie tricolori spettacolari (verde, bianco, rosso/rosa). Ama l\'umidità alta e la luce indiretta. Usa acqua piovana o filtrata.',
      en: 'Spectacular tricolor leaves (green, white, red/pink). Loves high humidity and indirect light. Use rainwater or filtered water.',
    },
    aliases: ['Tricolor ginger'],
  },
  {
    id: 'euphorbia-milii',
    commonName: 'Crown of Thorns',
    scientificName: 'Euphorbia milii',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 13,
    tempMax: 35,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'ATTENZIONE: la linfa lattiginosa è tossica. Ama molta luce solare. Annaffia raramente — tollera bene la siccità. Fiorisce quasi tutto l\'anno.',
      en: 'CAUTION: milky sap is toxic. Loves lots of sunlight. Water rarely — tolerates drought well. Blooms almost year-round.',
    },
    aliases: ['Christ plant', 'Christ thorn'],
  },
  {
    id: 'euphorbia-pulcherrima',
    commonName: 'Poinsettia',
    scientificName: 'Euphorbia pulcherrima',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 25,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta natalizia classica. Annaffia quando il terreno è secco in superficie. Evita temperature sotto i 15°C e correnti d\'aria. Per rifiorire ha bisogno di 14 ore di buio al giorno per 6 settimane.',
      en: 'Classic Christmas plant. Water when soil surface is dry. Avoid temperatures below 15°C and drafts. To rebloom needs 14 hours of darkness per day for 6 weeks.',
    },
    aliases: ['Christmas star', 'Christmas flower'],
  },
  {
    id: 'schlumbergera-truncata',
    commonName: 'Christmas Cactus',
    scientificName: 'Schlumbergera truncata',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 27,
    soil: 'Well-draining cactus mix with organic matter',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Non è un cactus del deserto — ama l\'umidità media. Per fiorire in inverno ha bisogno di 6 settimane di notti lunghe e fresche. Annaffia moderatamente.',
      en: 'Not a desert cactus — loves medium humidity. To bloom in winter needs 6 weeks of long cool nights. Water moderately.',
    },
    aliases: ['Holiday cactus', 'Thanksgiving cactus'],
  },
  {
    id: 'impatiens-walleriana',
    commonName: "Busy Lizzie",
    scientificName: 'Impatiens walleriana',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 27,
    soil: 'Moist, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Pianta da fiore generosa. Annaffia frequentemente e mantieni il terreno umido. Fiorisce in abbondanza con luce indiretta. Pizzica i germogli per incoraggiare la ramificazione.',
      en: 'Generous flowering plant. Water frequently and keep soil moist. Blooms abundantly with indirect light. Pinch shoots to encourage branching.',
    },
    aliases: ['Impatiens', 'Touch-me-not'],
  },
  {
    id: 'pelargonium-hortorum',
    commonName: 'Geranium',
    scientificName: 'Pelargonium hortorum',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 28,
    soil: 'Well-draining potting mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Classica pianta da balcone. Ama la luce solare diretta. Annaffia quando il terreno è asciutto. Rimuovi i fiori appassiti per prolungare la fioritura.',
      en: 'Classic balcony plant. Loves direct sunlight. Water when soil is dry. Remove spent flowers to prolong blooming.',
    },
    aliases: ['Zonal geranium'],
  },
  {
    id: 'primula-vulgaris',
    commonName: 'Common Primrose',
    scientificName: 'Primula vulgaris',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 5,
    tempMax: 18,
    soil: 'Moist, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta primaverile che ama il fresco. Annaffia regolarmente mantenendo il terreno umido. Rifiorisce se tenuta al fresco. Può causare allergie cutanee.',
      en: 'Spring plant that loves cool conditions. Water regularly keeping soil moist. Rebloms if kept cool. Can cause skin allergies.',
    },
    aliases: ['Primrose'],
  },
  {
    id: 'viola-tricolor',
    commonName: 'Pansy',
    scientificName: 'Viola tricolor',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 0,
    tempMax: 18,
    soil: 'Moist, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Fiori coloratissimi da primavera. Ama il fresco — soffre nel caldo estivo. Annaffia regolarmente. I fiori sono commestibili.',
      en: 'Very colorful spring flowers. Loves cool weather — suffers in summer heat. Water regularly. Flowers are edible.',
    },
    aliases: ['Viola', 'Heartease'],
  },
  {
    id: 'rosa-chinensis',
    commonName: 'Miniature Rose',
    scientificName: 'Rosa chinensis',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Rose in miniatura da interno o balcone. Ama molta luce solare. Annaffia regolarmente dalla base. Soggetta ad afidi e oidio — controlla regolarmente.',
      en: 'Miniature roses for indoors or balcony. Loves lots of sunlight. Water regularly from the base. Prone to aphids and powdery mildew — check regularly.',
    },
    aliases: ['China rose'],
  },
  {
    id: 'lavandula-angustifolia',
    commonName: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    waterFrequencyDays: 10,
    sunlight: 'full-sun',
    tempMin: -10,
    tempMax: 35,
    soil: 'Sandy, well-draining alkaline mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Ama la luce solare diretta e il terreno asciutto. Annaffia poco. Molto resistente una volta stabilita. Pota dopo la fioritura per mantenere la forma.',
      en: 'Loves direct sunlight and dry soil. Water sparingly. Very resilient once established. Prune after flowering to maintain shape.',
    },
    aliases: ['English lavender'],
  },
  {
    id: 'rosmarinus-officinalis',
    commonName: 'Rosemary',
    scientificName: 'Salvia rosmarinus',
    waterFrequencyDays: 10,
    sunlight: 'full-sun',
    tempMin: -5,
    tempMax: 35,
    soil: 'Sandy, well-draining soil',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Erba aromatica mediteranea. Ama luce piena e terreno ben drenato. Annaffia poco. Può diventare legnosa — pota regolarmente. Resistente al freddo.',
      en: 'Mediterranean aromatic herb. Loves full light and well-draining soil. Water sparingly. Can become woody — prune regularly. Cold resistant.',
    },
    aliases: ['Rosmarinus officinalis'],
  },
  {
    id: 'ocimum-basilicum',
    commonName: 'Basil',
    scientificName: 'Ocimum basilicum',
    waterFrequencyDays: 3,
    sunlight: 'full-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Rich, moist potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Erba aromatica da cucina. Annaffia frequentemente — non lasciare asciugare. Ama il sole diretto. Rimuovi i fiori per prolungare la vita fogliare. Sensibile al freddo.',
      en: 'Kitchen aromatic herb. Water frequently — do not let dry out. Loves direct sun. Remove flowers to prolong leaf life. Sensitive to cold.',
    },
    aliases: ['Sweet basil', 'Genovese basil'],
  },
  {
    id: 'mentha-spicata',
    commonName: 'Spearmint',
    scientificName: 'Mentha spicata',
    waterFrequencyDays: 3,
    sunlight: 'partial-sun',
    tempMin: 5,
    tempMax: 28,
    soil: 'Moist, rich potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Menta molto vigorosa. Coltiva in vaso per evitare che invada il giardino. Annaffia frequentemente. Taglia regolarmente per stimolare la crescita.',
      en: 'Very vigorous mint. Grow in a pot to prevent garden invasion. Water frequently. Trim regularly to stimulate growth.',
    },
    aliases: ['Mint', 'Garden mint'],
  },
  {
    id: 'thymus-vulgaris',
    commonName: 'Thyme',
    scientificName: 'Thymus vulgaris',
    waterFrequencyDays: 10,
    sunlight: 'full-sun',
    tempMin: -10,
    tempMax: 35,
    soil: 'Sandy, well-draining soil',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Erba aromatica mediterranea resistente. Ama il sole diretto e terreno asciutto. Annaffia poco. Ottima anche come pianta ornamentale.',
      en: 'Resistant Mediterranean aromatic herb. Loves direct sun and dry soil. Water sparingly. Also great as an ornamental plant.',
    },
    aliases: ['Common thyme', 'Garden thyme'],
  },
  {
    id: 'origanum-vulgare',
    commonName: 'Oregano',
    scientificName: 'Origanum vulgare',
    waterFrequencyDays: 10,
    sunlight: 'full-sun',
    tempMin: -5,
    tempMax: 35,
    soil: 'Sandy, well-draining soil',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Erba aromatica da pizza e pasta. Ama il sole e il terreno drenante. Annaffia poco. Taglia i fiori per mantenere il sapore delle foglie.',
      en: 'Aromatic herb for pizza and pasta. Loves sun and draining soil. Water sparingly. Cut flowers to maintain leaf flavor.',
    },
    aliases: ['Wild marjoram'],
  },
  {
    id: 'petroselinum-crispum',
    commonName: 'Parsley',
    scientificName: 'Petroselinum crispum',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 5,
    tempMax: 25,
    soil: 'Moist, rich potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Erba da cucina biennale. Annaffia regolarmente. Preferisce la luce indiretta o il sole del mattino. Raccogli dall\'esterno verso l\'interno.',
      en: 'Biennial kitchen herb. Water regularly. Prefers indirect light or morning sun. Harvest from outside inwards.',
    },
    aliases: ['Flat-leaf parsley', 'Curly parsley'],
  },
  {
    id: 'coriandrum-sativum',
    commonName: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    waterFrequencyDays: 3,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 25,
    soil: 'Moist, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Erba aromatica annuale che va a seme rapidamente. Tieni in un posto fresco. Semina frequentemente per continuità. Usa foglie giovani.',
      en: 'Annual aromatic herb that goes to seed quickly. Keep in a cool spot. Sow frequently for continuity. Use young leaves.',
    },
    aliases: ['Coriander', 'Chinese parsley'],
  },
  {
    id: 'heliotropium-arborescens',
    commonName: 'Heliotrope',
    scientificName: 'Heliotropium arborescens',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 28,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Profumata pianta da fiore. Ama il sole diretto. Annaffia regolarmente senza lasciare asciugare completamente. Fiorisce abbondantemente in estate.',
      en: 'Fragrant flowering plant. Loves direct sun. Water regularly without letting dry out completely. Blooms abundantly in summer.',
    },
    aliases: ['Cherry pie plant'],
  },
  {
    id: 'gardenia-jasminoides',
    commonName: 'Gardenia',
    scientificName: 'Gardenia jasminoides',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 28,
    soil: 'Acidic, well-draining mix',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: true,
    tips: {
      it: 'Profumatissima ma esigente. Ama l\'umidità alta e la luce indiretta brillante. Usa acqua a pH acido. Non spostare quando ha i boccioli — cadono.',
      en: 'Very fragrant but demanding. Loves high humidity and bright indirect light. Use pH-acidic water. Do not move when budding — they will drop.',
    },
    aliases: ['Cape jasmine'],
  },
  {
    id: 'jasinum-polyanthum',
    commonName: 'Pink Jasmine',
    scientificName: 'Jasminum polyanthum',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 25,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Gelsomino rampicante molto profumato. Ama il fresco per indurre la fioritura. Annaffia regolarmente in estate. Ha bisogno di un supporto su cui arrampicarsi.',
      en: 'Very fragrant climbing jasmine. Loves cool conditions to induce flowering. Water regularly in summer. Needs a support to climb.',
    },
    aliases: ['Winter jasmine', 'Chinese jasmine'],
  },
  {
    id: 'stephanotis-floribunda',
    commonName: 'Madagascar Jasmine',
    scientificName: 'Stephanotis floribunda',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 13,
    tempMax: 28,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Rampicante con fiori bianchi profumati. Ama la stabilità — non spostare. Annaffia regolarmente in estate. Sensibile all\'aria secca e al freddo.',
      en: 'Climber with fragrant white flowers. Loves stability — do not move. Water regularly in summer. Sensitive to dry air and cold.',
    },
    aliases: ['Bridal wreath', 'Wax flower'],
  },
  {
    id: 'bougainvillea-glabra',
    commonName: 'Bougainvillea',
    scientificName: 'Bougainvillea glabra',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 40,
    soil: 'Sandy, well-draining mix',
    humidity: 'low',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta spettacolare da esterno/balcone. Ama il sole intenso. Annaffia poco per stimolare la fioritura. Soffre il ristagno idrico. Taglia dopo la fioritura.',
      en: 'Spectacular outdoor/balcony plant. Loves intense sun. Water sparingly to stimulate flowering. Suffers waterlogging. Prune after flowering.',
    },
    aliases: ['Paper flower'],
  },
  {
    id: 'nerium-oleander',
    commonName: 'Oleander',
    scientificName: 'Nerium oleander',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: 5,
    tempMax: 40,
    soil: 'Well-draining potting mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'ATTENZIONE: pianta MOLTO TOSSICA — tutte le parti sono velenose. Ama il sole pieno. Tollera la siccità. Annaffia abbondantemente in estate.',
      en: 'CAUTION: VERY TOXIC plant — all parts are poisonous. Loves full sun. Tolerates drought. Water abundantly in summer.',
    },
    aliases: ['Rose laurel'],
  },
  {
    id: 'hibiscus-rosa-sinensis',
    commonName: 'Chinese Hibiscus',
    scientificName: 'Hibiscus rosa-sinensis',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 13,
    tempMax: 35,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Fiori spettacolari che durano un giorno. Ama il sole diretto. Annaffia abbondantemente in estate. Concima regolarmente. Porta in casa d\'inverno.',
      en: 'Spectacular flowers that last one day. Loves direct sun. Water abundantly in summer. Fertilize regularly. Bring indoors in winter.',
    },
    aliases: ['Tropical hibiscus', 'Rose of China'],
  },
  {
    id: 'wisteria-sinensis',
    commonName: 'Chinese Wisteria',
    scientificName: 'Wisteria sinensis',
    waterFrequencyDays: 7,
    sunlight: 'full-sun',
    tempMin: -15,
    tempMax: 35,
    soil: 'Rich, well-draining soil',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Rampicante spettacolare con fiori viola. Ama il sole pieno e lo spazio. Annaffia regolarmente. Pota drasticamente dopo la fioritura per controllarne la crescita.',
      en: 'Spectacular climber with purple flowers. Loves full sun and space. Water regularly. Prune drastically after flowering to control growth.',
    },
    aliases: ['Wisteria'],
  },
  {
    id: 'fuchsia-hybrida',
    commonName: 'Fuchsia',
    scientificName: 'Fuchsia hybrida',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 5,
    tempMax: 22,
    soil: 'Moist, well-draining mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Fiori bicolori penduli bellissimi. Ama il fresco e la luce indiretta. Annaffia frequentemente. Concima ogni 2 settimane. Ottima per cestini appesi.',
      en: 'Beautiful bicolor pendulous flowers. Loves cool conditions and indirect light. Water frequently. Fertilize every 2 weeks. Great for hanging baskets.',
    },
    aliases: ['Lady\'s eardrops'],
  },
  {
    id: 'ipomoea-batatas',
    commonName: 'Ornamental Sweet Potato Vine',
    scientificName: 'Ipomoea batatas',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 13,
    tempMax: 35,
    soil: 'Moist, well-draining mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Pianta ricadente dalle foglie colorate. Cresce rapidamente. Annaffia regolarmente. Ama il sole e il calore. Ottima per cestini appesi o bordure.',
      en: 'Trailing plant with colorful leaves. Grows rapidly. Water regularly. Loves sun and heat. Great for hanging baskets or borders.',
    },
    aliases: ['Sweet potato vine'],
  },
  {
    id: 'dionaea-muscipula',
    commonName: 'Venus Flytrap',
    scientificName: 'Dionaea muscipula',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 0,
    tempMax: 35,
    soil: 'Peat moss and perlite mix (no fertilizer)',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Pianta carnivora! Usa solo acqua distillata o piovana — l\'acqua del rubinetto la uccide. Ama il sole diretto. Non usare fertilizzanti. Lascia cacciare insetti naturalmente.',
      en: 'Carnivorous plant! Use only distilled or rainwater — tap water kills it. Loves direct sunlight. Never use fertilizers. Let it hunt insects naturally.',
    },
    aliases: ['Flytrap'],
  },
  {
    id: 'nepenthes-alata',
    commonName: 'Tropical Pitcher Plant',
    scientificName: 'Nepenthes alata',
    waterFrequencyDays: 5,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Sphagnum moss or peat mix (no fertilizer)',
    humidity: 'high',
    difficulty: 'hard',
    toxicPets: false,
    tips: {
      it: 'Pianta carnivora tropicale. Usa solo acqua distillata o piovana. Ama umidità altissima. Non usare fertilizzanti. I brocchetti contengono liquido digestivo.',
      en: 'Tropical carnivorous plant. Use only distilled or rainwater. Loves very high humidity. Never use fertilizers. Pitchers contain digestive liquid.',
    },
    aliases: ['Nepenthes', 'Monkey cups'],
  },
  {
    id: 'cyperus-alternifolius',
    commonName: 'Umbrella Papyrus',
    scientificName: 'Cyperus alternifolius',
    waterFrequencyDays: 3,
    sunlight: 'partial-sun',
    tempMin: 10,
    tempMax: 30,
    soil: 'Moist or even wet soil',
    humidity: 'high',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta acquatica o semi-acquatica. Ama il terreno sempre umido o sommerso. Tieni il sottovaso sempre con acqua. Tollera la poca luce.',
      en: 'Aquatic or semi-aquatic plant. Loves consistently moist or submerged soil. Keep saucer always with water. Tolerates low light.',
    },
    aliases: ['Umbrella plant', 'Parasol plant'],
  },
  {
    id: 'pistia-stratiotes',
    commonName: 'Water Lettuce',
    scientificName: 'Pistia stratiotes',
    waterFrequencyDays: 1,
    sunlight: 'partial-sun',
    tempMin: 18,
    tempMax: 35,
    humidity: 'high',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Pianta acquatica galleggiante. Vive sopra l\'acqua, le radici assorbono i nutrienti direttamente dall\'acqua. Ama il calore e la luce indiretta.',
      en: 'Floating aquatic plant. Lives on water surface, roots absorb nutrients directly from water. Loves warmth and indirect light.',
    },
    aliases: ['Tropical duckweed'],
  },
  {
    id: 'nymphaea-tetragona',
    commonName: 'Water Lily',
    scientificName: 'Nymphaea tetragona',
    waterFrequencyDays: 1,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 35,
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Ninfea da laghetto o vaso d\'acqua grande. Ha bisogno di luce solare diretta per fiorire. In inverno va in dormienza sul fondo.',
      en: 'Water lily for ponds or large water containers. Needs direct sunlight to bloom. Goes dormant at the bottom in winter.',
    },
    aliases: ['Dwarf water lily'],
  },
  {
    id: 'bambusa-vulgaris',
    commonName: 'Common Bamboo',
    scientificName: 'Bambusa vulgaris',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 40,
    soil: 'Rich, moist potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Bambù tropicale da grandi spazi. Cresce molto rapidamente. Annaffia abbondantemente. Ama il sole e il calore. In vaso limita la crescita.',
      en: 'Tropical bamboo for large spaces. Grows very rapidly. Water abundantly. Loves sun and warmth. In a pot it limits growth.',
    },
    aliases: ['Bamboo'],
  },
  {
    id: 'dracaena-fragrans',
    commonName: 'Corn Plant',
    scientificName: 'Dracaena fragrans',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Tollera la neglect meglio di quasi qualsiasi altra pianta. Annaffia poco. Evita acqua con fluoro. Senescenza delle foglie inferiori è normale.',
      en: 'Tolerates neglect better than almost any plant. Water sparingly. Avoid fluorinated water. Lower leaf senescence is normal.',
    },
    aliases: ['Happy plant', 'Mass cane'],
  },
  {
    id: 'dracaena-reflexa',
    commonName: "Song of India",
    scientificName: 'Dracaena reflexa',
    waterFrequencyDays: 14,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Pianta elegante con foglie verdi e gialle. Annaffia moderatamente e lascia asciugare tra le annaffiature. Tollera la poca luce. Sensibile al fluoro.',
      en: 'Elegant plant with green and yellow leaves. Water moderately and allow drying between waterings. Tolerates low light. Sensitive to fluoride.',
    },
    aliases: ['Pleomele'],
  },
  {
    id: 'beaucarnea-recurvata',
    commonName: 'Ponytail Palm',
    scientificName: 'Beaucarnea recurvata',
    waterFrequencyDays: 21,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 35,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Non è una vera palma — è una succulenta! Accumula acqua nel bulbo basale. Annaffia raramente. Ama molta luce. Quasi impossibile da uccidere.',
      en: 'Not a real palm — it\'s a succulent! Stores water in the basal bulb. Water rarely. Loves lots of light. Nearly impossible to kill.',
    },
    aliases: ['Bottle palm', 'Elephant foot'],
  },
  {
    id: 'pachira-aquatica',
    commonName: 'Money Tree',
    scientificName: 'Pachira aquatica',
    waterFrequencyDays: 10,
    sunlight: 'partial-sun',
    tempMin: 16,
    tempMax: 30,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: false,
    tips: {
      it: 'Albero della fortuna con tronco intrecciato. Annaffia quando il terreno è parzialmente asciutto. Ama la luce indiretta. Facile da coltivare.',
      en: 'Good luck tree with braided trunk. Water when soil is partially dry. Loves indirect light. Easy to grow.',
    },
    aliases: ['Guiana chestnut'],
  },
  {
    id: 'adenium-obesum',
    commonName: 'Desert Rose',
    scientificName: 'Adenium obesum',
    waterFrequencyDays: 14,
    sunlight: 'full-sun',
    tempMin: 13,
    tempMax: 40,
    soil: 'Sandy, well-draining cactus mix',
    humidity: 'low',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Pianta succulenta con caudex prominente. Ama il calore e il sole pieno. Annaffia raramente. In inverno tieni asciutto. La linfa è tossica.',
      en: 'Succulent plant with prominent caudex. Loves heat and full sun. Water rarely. Keep dry in winter. Sap is toxic.',
    },
    aliases: ['Mock azalea', 'Sabi star'],
  },
  {
    id: 'columnea-gloriosa',
    commonName: 'Goldfish Plant',
    scientificName: 'Columnea gloriosa',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 15,
    tempMax: 28,
    soil: 'Light, well-draining mix',
    humidity: 'high',
    difficulty: 'medium',
    toxicPets: false,
    tips: {
      it: 'Pianta ricadente con fiori arancioni a forma di pesce rosso. Ama l\'umidità alta. Annaffia regolarmente. Ottima per cestini appesi.',
      en: 'Trailing plant with orange goldfish-shaped flowers. Loves high humidity. Water regularly. Great for hanging baskets.',
    },
    aliases: ['Goldfish plant'],
  },
  {
    id: 'ardisia-crenata',
    commonName: 'Coral Berry',
    scientificName: 'Ardisia crenata',
    waterFrequencyDays: 7,
    sunlight: 'partial-sun',
    tempMin: 12,
    tempMax: 25,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'Arbusto decorativo con bacche rosse persistenti. Ama il fresco e la luce indiretta. Annaffia regolarmente. Nebulizza per aumentare l\'umidità.',
      en: 'Decorative shrub with persistent red berries. Loves cool conditions and indirect light. Water regularly. Mist to increase humidity.',
    },
    aliases: ['Spiceberry', 'Christmas berry'],
  },
  {
    id: 'solanum-pseudocapsicum',
    commonName: 'Jerusalem Cherry',
    scientificName: 'Solanum pseudocapsicum',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 10,
    tempMax: 28,
    soil: 'Well-draining potting mix',
    humidity: 'medium',
    difficulty: 'medium',
    toxicPets: true,
    tips: {
      it: 'ATTENZIONE: i frutti arancioni sono tossici per uomini e animali. Pianta decorativa invernale. Ama il sole. Annaffia regolarmente.',
      en: 'CAUTION: orange fruits are toxic to humans and pets. Winter decorative plant. Loves sun. Water regularly.',
    },
    aliases: ['Winter cherry', 'Madeira winter cherry'],
  },
  {
    id: 'capsicum-annuum',
    commonName: 'Ornamental Pepper',
    scientificName: 'Capsicum annuum',
    waterFrequencyDays: 5,
    sunlight: 'full-sun',
    tempMin: 15,
    tempMax: 30,
    soil: 'Rich, well-draining potting mix',
    humidity: 'medium',
    difficulty: 'easy',
    toxicPets: true,
    tips: {
      it: 'Peperoncino ornamentale con frutti colorati. Ama molta luce solare. Annaffia regolarmente senza lasciare asciugare. I frutti piccanti sono commestibili.',
      en: 'Ornamental pepper with colorful fruits. Loves lots of sunlight. Water regularly without letting dry. Spicy fruits are edible.',
    },
    aliases: ['Christmas pepper', 'Chili pepper'],
  },
];

export function getCareInfo(scientificName: string): PlantCareInfo | null {
  return (
    CARE_DATA.find(
      (plant) =>
        plant.scientificName.toLowerCase() === scientificName.toLowerCase()
    ) || null
  );
}

export default CARE_DATA;
